# fly.toml app configuration file generated for speechmanagement on 2023-07-26T08:22:41+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "speechmanagement"
primary_region = "hkg"

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
